package pokemon;

/**
 * Questa classe rappresenta le abilità che possono essere possedute dai Pokémon.
 */
public enum Ability {
	ADAPTABILITY("Powers up moves of the same type"),
	AERILATE("Turns Normal-type moves into Flying-type moves"),
	AFTERMATH("Damages the attacker landing the finishing hit"),
	AIR_LOCK("Eliminates the effects of weather"),
	ANALYTIC("Boosts move power when the Pokémon moves last"),
	ANGER_POINT("Maxes Attack after taking a critical hit"),
	ANGER_SHELL("Lowers Defense/Sp. Def and raises Attack/Sp. Atk/Speed when HP drops below half"),
	ANTICIPATION("Senses a foe's dangerous moves"),
	ARENA_TRAP("Prevents the foe from fleeing"),
	ARMOR_TAIL("Prevents opponent using priority moves"),
	AROMA_VEIL("Protects allies from attacks that limit their move choices"),
	AS_ONE("Combines Unnerve and Chilling Neigh/Grim Neigh"),
	AURA_BREAK("Reduces power of Dark- and Fairy-type moves"),
	BAD_DREAMS("Reduces a sleeping foe's HP"),
	BALL_FETCH("Retrieves a Poké Ball from a failed throw"),
	BATTERY("Raises power of teammates' Special moves"),
	BATTLE_ARMOR("The Pokémon is protected against critical hits"),
	BATTLE_BOND("Transform into Ash-Greninja after causing opponent to faint"),
	BEADS_OF_RUIN("Lowers Special Defense of all Pokémon except itself"),
	BEAST_BOOST("The Pokémon boosts its most proficient stat each time it knocks out a Pokémon"),
	BERSERK("Raises Special Attack when HP drops below half"),
	BIG_PECKS("Protects the Pokémon from Defense-lowering attacks"),
	BLAZE("Powers up Fire-type moves in a pinch"),
	BULLETPROOF("Protects the Pokémon from ball and bomb moves"),
	CHEEK_POUCH("Restores additional HP when a Berry is consumed"),
	CHILLING_NEIGH("Boosts Attack after knocking out a Pokémon"),
	CHLOROPHYLL("Boosts the Pokémon's Speed in sunshine"),
	CLEAR_BODY("Prevents other Pokémon from lowering its stats"),
	CLOUD_NINE("Eliminates the effects of weather"),
	COLOR_CHANGE("Changes the Pokémon's type to the foe's move"),
	COMATOSE("The Pokémon is always asleep but can still attack"),
	COMMANDER("Goes inside the mouth of an ally Dondozo if one is on the field"),
	COMPETITIVE("Sharply raises Special Attack when the Pokémon's stats are lowered"),
	COMPOUND_EYES("The Pokémon's accuracy is boosted"),
	CONTRARY("Makes stat changes have an opposite effect"),
	CORROSION("The Pokémon can poison Steel and Poison types"),
	COSTAR("Copies ally's stat changes on entering battle"),
	COTTON_DOWN("Lowers foe's Speed when hit"),
	CUD_CHEW("Can eat the same Berry twice"),
	CURIOUS_MEDICINE("Resets all stat changes upon entering battlefield"),
	CURSED_BODY("May disable a move used on the Pokémon"),
	CUTE_CHARM("Contact with the Pokémon may cause infatuation"),
	DAMP("Prevents the use of self-destructing moves"),
	DANCER("Copies the foe's Dance moves"),
	DARK_AURA("Raises power of Dark type moves for all Pokémon in battle"),
	DAUNTLESS_SHIELD("Boosts Defense in battle"),
	DAZZLING("Protects the Pokémon from high-priority moves"),
	DEFEATIST("Lowers stats when HP drops below half"),
	DEFIANT("Sharply raises Attack when the Pokémon's stats are lowered"),
	DELTA_STREAM("Creates strong winds when the ability activates"),
	DISGUISE("Avoids damage for one turn"),
	DOWNLOAD("Adjusts power according to a foe's defenses"),
	DRAGONS_MAW("Powers up Dragon-type moves"),
	DRIZZLE("The Pokémon makes it rain when it enters a battle"),
	DROUGHT("Turns the sunlight harsh when the Pokémon enters a battle"),
	DRY_SKIN("Reduces HP if it is hot. Water restores HP"),
	EARLY_BIRD("The Pokémon awakens quickly from sleep"),
	EARTH_EATER("Restores HP when hit by a Ground-type move"),
	EFFECT_SPORE("Contact may poison or cause paralysis or sleep"),
	ELECTRIC_SURGE("The Pokémon creates an Electric Terrain when it enters a battle"),
	ELECTROMORPHOSIS("Doubles power of the next Electric-type move when hit by an attack"),
	EMBODY_ASPECT("Boosts Attack/Defense/Sp. Def/Speed depending on the form"),
	EMERGENCY_EXIT("Switches out when HP falls below 50%"),
	FAIRY_AURA("Raises power of Fairy type moves for all Pokémon in battle"),
	FILTER("Reduces damage from super-effective attacks"),
	FLAME_BODY("Contact with the Pokémon may burn the attacker"),
	FLARE_BOOST("Powers up Special moves when burned"),
	FLASH_FIRE("Powers up Fire-type moves when hit"),
	FLOWER_GIFT("Powers up party Pokémon when it is sunny"),
	FLOWER_VEIL("Prevents lowering of ally Grass-type Pokémon's stats"),
	FLUFFY("Halves the damage taken from contact moves"),
	FORECAST("Transforms with the weather"),
	FOREWARN("Determines what moves a foe has"),
	FRIEND_GUARD("Reduces damage done to allies"),
	FRISK("Reveals the foe's held item"),
	FULL_METAL_BODY("Prevents other Pokémon from lowering its stats"),
	FUR_COAT("Halves damage from physical moves"),
	GALE_WINGS("Gives priority to Flying-type moves when HP is full"),
	GALVANIZE("Turns Normal moves into Electric moves and powers them up"),
	GLUTTONY("Encourages the early use of a held Berry"),
	GOOD_AS_GOLD("Protects the Pokémon from status conditions"),
	GOOEY("Contact with the Pokémon lowers the attacker's Speed"),
	GORILLA_TACTICS("Boosts the Pokémon's Attack but only allows the use of the first selected move"),
	GRASS_PELT("Raises Defense in Grassy Terrain"),
	GRASSY_SURGE("Turns the ground into Grassy Terrain when entering battle"),
	GRIM_NEIGH("Boosts Special Attack after knocking out a Pokémon"),
	GUARD_DOG("Boosts Defense/Sp. Def of itself and allies when hit by Dark-type moves"),
	GULP_MISSILE("Turns into Ice/Flying type and may cause confusion"),
	GUTS("Boosts Attack if there is a status problem"),
	HADRON_ENGINE("Moves 1 stage higher priority under gravity"),
	HARVEST("May create another Berry after one is used"),
	HEALER("May heal an ally's status conditions"),
	HEATPROOF("Weakens the power of Fire-type moves"),
	HEAVY_METAL("Doubles the Pokémon's weight"),
	HONEY_GATHER("May gather Honey after a battle"),
	HOSPITALITY("The Pokémon may heal an ally's status conditions"),
	HUGE_POWER("Doubles the Pokémon's Attack stat"),
	HUNGER_SWITCH("Transforms depending on eaten Berry"),
	HUSTLE("Boosts the Attack stat but lowers accuracy"),
	HYDRATION("Heals status conditions if it is raining"),
	HYPER_CUTTER("The Pokémon's cutting moves are strong"),
	ICE_BODY("The Pokémon regains HP in a hailstorm"),
	ICE_FACE("Changes forms depending on the weather"),
	ICE_SCALES("The Pokémon is protected by ice scales"),
	ILLUMINATE("Raises the likelihood of meeting wild Pokémon"),
	ILLUSION("Takes on the appearance and abilities of a party Pokémon"),
	IMMUNITY("Prevents the Pokémon from getting poisoned"),
	IMPOSTER("The Pokémon transforms itself into the Pokémon it's facing"),
	INFILTRATOR("Passes through the foe's barrier and strikes"),
	INNARDS_OUT("Damages the attacker landing the finishing hit"),
	INNER_FOCUS("The Pokémon is protected from flinching"),
	INSOMNIA("Prevents the Pokémon from falling asleep"),
	INTIMIDATE("Lowers the opposing Pokémon's Attack stat"),
	INTREPID_SWORD("Raises Attack on entering a battle"),
	IRON_BARBS("Deals damage when hit by a move"),  
	ZEN_MODE("Changes form when HP drops below half."),  
	WONDER_SKIN("Makes status-changing moves more likely to miss."),  
	WONDER_GUARD("Only supereffective moves will hit."),  
	WIND_RIDER("Takes no damage from wind moves, and boosts Attack if hit by one."),  
	WIND_POWER("Doubles power of the next Electric-type move used, when hit by a wind move."),  
	WIMP_OUT("Switches out when HP drops below half."),  
	WHITE_SMOKE("Prevents other Pokémon from lowering its stats."),  
	WELL_BAKED_BODY("Immune to Fire-type moves, and Defense is sharply boosted."),  
	WEAK_ARMOR("Physical attacks lower Defense and raise Speed."),  
	WATER_VEIL("Prevents the Pokémon from getting a burn."),  
	WATER_COMPACTION("Sharply raises Defense when hit by a Water-type move."),  
	WATER_BUBBLE("Halves damage from Fire-type moves, doubles power of Water-type moves used, and prevents burns."),  
	WATER_ABSORB("Restores HP if hit by a Water-type move."),  
	WANDERING_SPIRIT("Swaps abilities with opponents on contact."),  
	VOLT_ABSORB("Restores HP if hit by an Electric-type move."),  
	VITAL_SPIRIT("Prevents the Pokémon from falling asleep."),  
	VICTORY_STAR("Boosts the accuracy of its allies and itself."),  
	VESSEL_OF_RUIN("Lowers Special Attack of all Pokémon except itself."),  
	UNSEEN_FIST("Contact moves can strike through Protect/Detect."),  
	UNNERVE("Makes the foe nervous and unable to eat Berries."),  
	UNBURDEN("Raises Speed if a held item is used."),  
	UNAWARE("Ignores any stat changes in the Pokémon."),  
	TURBOBLAZE("Moves can be used regardless of Abilities."),  
	TRUANT("Pokémon can't attack on consecutive turns."),  
	TRIAGE("Gives priority to restorative moves."),  
	TRANSISTOR("Powers up Electric-type moves."),  
	TRACE("The Pokémon copies a foe's Ability."),  
	TOXIC_DEBRIS("Scatters poison spikes at the feet of the opposing team when the Pokémon takes damage from physical moves."),  
	TOXIC_CHAIN("May cause bad poisoning."),  
	TOXIC_BOOST("Powers up physical attacks when poisoned."),  
	TOUGH_CLAWS("Boosts the power of contact moves."),  
	TORRENT("Powers up Water-type moves in a pinch."),  
	TINTED_LENS("Powers up “not very effective” moves."),  
	THICK_FAT("Ups resistance to Fire- and Ice-type moves."),  
	THERMAL_EXCHANGE("Raises Attack when hit by a Fire-type move. Cannot be burned."),  
	TERAVOLT("Moves can be used regardless of Abilities."),  
	TERA_SHIFT("Transforms into Terastal Form in battle."),  
	TERA_SHELL("Moves are not very effective when HP is full."),  
	TELEPATHY("Anticipates an ally's attack and dodges it."),  
	TECHNICIAN("Powers up the Pokémon's weaker moves."),  
	TANGLING_HAIR("Contact with the Pokémon lowers the attacker's Speed stat."),  
	TANGLED_FEET("Raises evasion if the Pokémon is confused."),  
	SYNCHRONIZE("Passes a burn, poison, or paralysis to the foe."),  
	SYMBIOSIS("The Pokémon can pass an item to an ally."),  
	SWORD_OF_RUIN("Lowers Defense of all Pokémon except itself."),  
	SWIFT_SWIM("Boosts the Pokémon's Speed in rain."),  
	SWEET_VEIL("Prevents the Pokémon and allies from falling asleep."),  
	SWARM("Powers up Bug-type moves in a pinch."),  
	SURGE_SURFER("Doubles Speed during Electric Terrain."),  
	SUPREME_OVERLORD("Attack and Special Attack are boosted for each party Pokémon that has been defeated."),  
	SUPER_SWEET_SYRUP("Lowers opponent's Evasiveness when entering battle."),  
	SUPER_LUCK("Heightens the critical-hit ratios of moves."),  
	SUCTION_CUPS("Negates all moves that force switching out."),  
	STURDY("It cannot be knocked out with one hit."),  
	STRONG_JAW("Boosts the power of biting moves."),  
	STORM_DRAIN("Draws in all Water-type moves to up Sp. Attack."),  
	STICKY_HOLD("Protects the Pokémon from item theft."),  
	STENCH("The stench may cause the target to flinch."),  
	STEELY_SPIRIT("Powers up ally Pokémon's Steel-type moves."),  
	STEELWORKER("Powers up Steel-type moves."),  
	STEAM_ENGINE("Drastically raises Speed when hit by a Fire- or Water-type move."),  
	STEADFAST("Raises Speed each time the Pokémon flinches."),  
	STATIC("Contact with the Pokémon may cause paralysis."),  
	STANCE_CHANGE("Changes form depending on moves used."),  
	STAMINA("Raises Defense when attacked."),  
	STALL("The Pokémon moves after all other Pokémon do."),  
	STAKEOUT("Powers up moves against Pokémon that are switching out."),  
	SPEED_BOOST("Its Speed stat is gradually boosted."),  
	SOUNDPROOF("Sound-based moves have no effect on the Pokémon."),  
	SOUL_HEART("Raises Sp. Attack each time a Pokémon faints."),  
	SOLID_ROCK("Powers down the foe's supereffective moves."),  
	SOLAR_POWER("Boosts Sp. Atk, but lowers HP in sunshine."),  
	SNOW_WARNING("The Pokémon summons a hailstorm in battle."),  
	SNOW_CLOAK("Raises evasion in a hailstorm."),  
	SNIPER("Powers up moves if they become critical hits."),  
	SLUSH_RUSH("Boosts the Pokémon's Speed stat in a hailstorm."),  
	SLOW_START("Temporarily halves Attack and Speed."),  
	SKILL_LINK("Increases frequency of multi-strike moves."),  
	SIMPLE("The Pokémon is prone to wild stat changes."),  
	SHELL_ARMOR("Protects the Pokémon from critical hits."),  
	SHEER_FORCE("Removes added effects to increase move damage."),  
	SHED_SKIN("The Pokémon may heal its own status conditions."),  
	SHARPNESS("Raises the Pokémon's Attack when it knocks out a target."),  
	SHADOW_TAG("Prevents the foe from escaping."),  
	SHADOW_SHIELD("Halves damage from physical moves when HP is full."),  
	SERENE_GRACE("Boosts the likelihood of added effects appearing."),  
	SEED_SOWER("Seeds itself with status condition-inducing berries."),  
	SCREEN_CLEANER("Removes entry hazards and screens when the Pokémon enters battle."),  
	SCRAPPY("Enables moves to hit Ghost-type Pokémon."),  
	SCHOOLING("When it has a lot of HP, it forms a powerful school."),  
	SAPSIPPER("Boosts Attack when hit by a Grass-type move, and prevents moves from lowering Attack."),  
	SAND_VEIL("Boosts evasion in a sandstorm."),  
	SAND_STREAM("The Pokémon summons a sandstorm in battle."),  
	SAND_SPIT("Sandstorm immunity. This Pokémon does not take damage from Sandstorm."),  
	SAND_RUSH("Boosts the Pokémon's Speed stat in a sandstorm."),  
	SAND_FORCE("Boosts the power of Rock-, Ground-, and Steel-type moves in a sandstorm."),  
	RUN_AWAY("Makes fleeing from battle easier."),  
	ROUGH_SKIN("Inflicts damage to the attacker on contact."),  
	ROCKY_PAYLOAD("Leaves rocks in the opponent's path."),  
	ROCK_HEAD("Protects the Pokémon from recoil damage."),  
	RKS_SYSTEM("Changes type and form depending on the Drive being used."),  
	RIVALRY("Becomes more powerful if the foe is of the same gender."),  
	RIPEN("Doubles the effect of berries."),  
	REGENERATOR("Restores HP when withdrawn from battle."),  
	REFRIGERATE("Turns Normal-type moves into Ice-type moves."),  
	RECKLESS("Boosts the power of moves that have recoil damage."),  
	RECEIVER("Inherits an ally's Ability when it faints."),  
	RATTLED("Boosts Speed if hit by a Bug-, Ghost-, or Dark-type move."),  
	RAIN_DISH("The Pokémon gradually regains HP in rain."),  
	QUICK_FEET("Boosts Speed if there is a status problem."),  
	QUICK_DRAW("Gives priority to Flying-type moves."),  
	QUEENLY_MAJESTY("Gives priority to Fairy-type moves."),  
	QUARK_DRIVE("The Pokémon's type changes to match the type of the move it uses."),  
	PURIFYING_SALT("Removes the effects of waterlogged."),  
	PURE_POWER("Raises Attack."),  
	PUNK_ROCK("Boosts the power of sound-based moves."),  
	PSYCHIC_SURGE("Turns the ground into Psychic Terrain when the Pokémon enters battle."),  
	PROTO_SYNTHESIS("The Pokémon's type changes to match the type of the move it uses."),  
	PROTECTIVE_PADS("Protects the Pokémon from the effects of trap moves."),  
	PROPELLER_TAIL("Makes the Pokémon's moves always hit the target."),  
	PROPULSION("Speed is boosted when the Pokémon's stats are lowered."),    
	PROPHETIC_SYNTHESIS("The Pokémon's type changes to match the type of the move it uses."),  
	PRIORITY_QUEUE("Gives priority to status moves."),  
	POWER_SPOT("Powers up ally Pokémon's moves."),  
	POWER_OF_ALCHEMY("The Pokémon's type changes to match the type of the move it uses."),  
	POWER_CONSTRUCT("Changes form when HP drops below half."),  
	POISON_TOUCH("May poison targets when a Pokémon makes contact."),  
	POISON_PUPPETEER("Makes the opponent Poison-type."),  
	POISON_POINT("Contact with the Pokémon may poison the attacker."),  
	POISON_HEAL("Restores HP if the Pokémon is poisoned."),  
	PLUS("Raises Sp. Atk if another Pokémon has Minus."),  
	PIXILATE("Turns Normal-type moves into Fairy-type moves."),  
	PICKUP("The Pokémon may pick up items."),  
	PICKPOCKET("Steals an item when hit by another Pokémon."),  
	PERISH_BODY("Raises Defense if the Pokémon's hit points are low."),  
	PASTEL_VEIL("Prevents the Pokémon and allies from being poisoned."),  
	PARENTAL_BOND("Allows the Pokémon to attack twice."),  
	OWN_TEMPO("Prevents the Pokémon from becoming confused."),  
	OVERGROW("Powers up Grass-type moves in a pinch."),  
	OVERCOAT("Protects the Pokémon from weather damage."),  
	ORICHALCUM_PULSE("The Pokémon's type changes to match the type of the move it uses."),  
	OPPORTUNIST("Boosts the Pokémon's Speed stat if it is hit by a move of its weaker spot."),  
	OBLIVIOUS("Prevents the Pokémon from becoming infatuated."),  
	NUTRITIONIST("Heals status conditions if it is raining."),  
	NOTICE_BOARD("Automatically uses a status move if the user is a bystander."),  
	NO_GUARD("Ensures attacks by or against the Pokémon land."),  
	NEUTRALIZING_GAS("Removes the Abilities of opponents."),  
	NEUROFORCE("Powers up moves that are super effective."),  
	NATURAL_CURE("Heals upon switching out."),  
	MYCELIUM_MIGHT("Powers up moves when the Pokémon's HP is low."),  
	MUMMY("Contact with the Pokémon changes the attacker's Ability."),  
	MULTITYPE("Changes type depending on its held Plate."),  
	MULTISCALE("Reduces damage taken when HP is full."),  
	MOXIE("Raises Attack one stage upon knocking out another Pokémon."),  
	MOTOR_DRIVE("Boosts Speed if hit by an Electric-type move."),  
	MOODY("Raises one stat and lowers another."),  
	MOLD_BREAKER("Moves can be used on the target regardless of its Abilities."),  
	MISTY_SURGE("Turns the ground into Misty Terrain when the Pokémon enters battle."),  
	MIRROR_ARMOR("Bounces back only the stat-lowering effects of attacks."),  
	MINUS("Raises Sp. Atk if an ally has Plus.");

	private String ability;

	/**
     * Costruttore per l'oggetto Ability.
     * 
     * @param ability Il nome dell'abilità.
     */
	private Ability(String string) {
		this.ability=ability;

}

	 /**
     * Override del metodo toString per ottenere una rappresentazione leggibile del nome dell'abilità.
     * 
     * @return Il nome dell'abilità in formato leggibile.
     */
	@Override
	public String toString() {
		return (name().charAt(0)+name().substring(1).toLowerCase()).replace("_", " ");
}
}